#!/usr/bin/env node
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

interface Message {
  role: 'user' | 'assistant';
  content: any;
  timestamp?: string;
  type?: string;
  toolUseResult?: any;
  message?: any;
}

interface StateTracker {
  lastProcessedTimestamp: string;
  totalSessions: number;
}

interface Session {
  userRequests: string[];
  claudeActions: string[];
  errors: string[];
  filesModified: string[];
  toolsUsed: string[];
  timestamp: string;
}

const CLAUDE_HOME = path.join(os.homedir(), '.claude');
const STATE_FILE = '.session-doc-state.json';

/**
 * 현재 프로젝트의 대화 세션 파일 경로를 찾습니다
 */
function findProjectSessionFiles(projectPath: string): string[] {
  const normalizedPath = projectPath.replace(/[/.]/g, '-');
  const projectDir = path.join(CLAUDE_HOME, 'projects', normalizedPath);

  if (!fs.existsSync(projectDir)) {
    return [];
  }

  const files = fs.readdirSync(projectDir);
  const sessionFiles = files
    .filter(f => f.endsWith('.jsonl') && !f.startsWith('agent-'))
    .map(f => path.join(projectDir, f))
    .filter(f => fs.statSync(f).size > 0);

  return sessionFiles;
}

/**
 * JSONL 파일에서 메시지들을 읽어옵니다
 */
function readMessages(filePath: string, lastTimestamp?: string): Message[] {
  const messages: Message[] = [];
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.trim().split('\n').filter(line => line.trim());

  for (const line of lines) {
    try {
      const msg = JSON.parse(line);

      if (lastTimestamp && msg.timestamp) {
        const msgTime = new Date(msg.timestamp).getTime();
        const lastTime = new Date(lastTimestamp).getTime();
        if (msgTime <= lastTime) {
          continue;
        }
      }

      messages.push(msg);
    } catch (e) {
      continue;
    }
  }

  return messages;
}

/**
 * 시스템 태그를 제거합니다
 */
function removeSystemTags(text: string): string {
  const patterns = [
    /<ide_opened_file>[\s\S]*?<\/ide_opened_file>/g,
    /<ide_selection>[\s\S]*?<\/ide_selection>/g,
    /<system-reminder>[\s\S]*?<\/system-reminder>/g,
    /<user-prompt-submit-hook>[\s\S]*?<\/user-prompt-submit-hook>/g,
    /<command-message>[\s\S]*?<\/command-message>/g,
    /<command-name>[\s\S]*?<\/command-name>/g,
    /<command-args>[\s\S]*?<\/command-args>/g,
    /<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g,
    /\[Request interrupted by user.*?\]/g,
    /Caveat: The messages below were generated by.*?explicitly asks you to\./gs,
  ];

  let cleaned = text;
  for (const pattern of patterns) {
    cleaned = cleaned.replace(pattern, '');
  }

  return cleaned.trim();
}

/**
 * 무의미한 메시지인지 확인합니다
 */
function isNoiseMessage(text: string): boolean {
  if (!text || text.length === 0) return true;

  const noisePatterns = [
    /^#\s*\/session-doc/,
    /^#\s*\/[\w-]+\s*-/,
    /^\[Request interrupted/,
    /^Caveat: The messages below/,
    /^<command-/,
    /^<local-command/,
    /^mkdir -p \.claude\/commands/,
    /^git clone.*session-doc/,
    /^TOOL_PATH=.*session-doc/,
  ];

  return noisePatterns.some(pattern => pattern.test(text.trim()));
}

/**
 * 유효한 사용자 요청인지 확인합니다
 */
function isValidUserRequest(text: string): boolean {
  if (!text || text.length < 2) return false;

  const invalidPatterns = [
    /^\[Request interrupted/,
    /^<command-/,
    /^<local-command/,
    /^Caveat:/,
    /^#\s*\/[\w-]+\s*-/,  // 슬래시 커맨드 설명 (예: # /session-doc - ...)
  ];

  return !invalidPatterns.some(pattern => pattern.test(text.trim()));
}

/**
 * 메시지에서 텍스트 콘텐츠를 추출합니다
 */
function extractTextContent(message: Message): string | undefined {
  const content = message.message?.content || message.content;

  if (typeof content === 'string') {
    return removeSystemTags(content);
  }

  if (Array.isArray(content)) {
    const textContent = content
      .filter(c => c.type === 'text')
      .map(c => c.text)
      .join('\n');

    if (textContent.trim()) {
      return removeSystemTags(textContent);
    }
  }

  return undefined;
}

/**
 * 파일 경로에서 파일명만 추출합니다
 */
function getFileName(filePath: string): string {
  return path.basename(filePath);
}

/**
 * 도구 호출에서 정보를 추출합니다
 */
function extractToolInfo(message: Message): { tools: string[], files: string[], errors: string[] } {
  const tools: string[] = [];
  const files: string[] = [];
  const errors: string[] = [];

  if (message.message?.content && Array.isArray(message.message.content)) {
    for (const item of message.message.content) {
      if (item.type === 'tool_use') {
        const toolName = item.name || 'unknown';
        const input = item.input || {};

        tools.push(toolName);

        if (input.file_path) {
          files.push(getFileName(input.file_path));
        }
      }
    }
  }

  // 에러 추출
  if (message.toolUseResult?.content) {
    const resultContent = message.toolUseResult.content;
    if (typeof resultContent === 'string' && resultContent.includes('Exit code')) {
      const errorMatch = resultContent.match(/Exit code \d+[\s\S]*?(?=\n\n|$)/);
      if (errorMatch) {
        errors.push(errorMatch[0].substring(0, 200));
      }
    }
  }

  return { tools: [...new Set(tools)], files: [...new Set(files)], errors };
}

/**
 * 도구 사용을 비개발자 친화적으로 변환합니다
 */
function translateToolUsage(tools: string[], files: string[]): string[] {
  const actions: string[] = [];
  const toolActions: Record<string, string> = {
    'Read': '파일 확인',
    'Write': '파일 생성',
    'Edit': '파일 수정',
    'Bash': '명령어 실행',
    'Glob': '파일 검색',
    'Grep': '코드 검색',
    'Task': '하위 작업 수행',
    'WebFetch': '웹 정보 조회',
    'WebSearch': '웹 검색',
    'AskUserQuestion': '사용자에게 질문',
    'TodoWrite': '작업 목록 관리',
  };

  const usedActions = new Set<string>();

  for (const tool of tools) {
    const action = toolActions[tool] || tool;
    if (!usedActions.has(action)) {
      usedActions.add(action);

      if ((tool === 'Read' || tool === 'Write' || tool === 'Edit') && files.length > 0) {
        const fileList = files.length > 3
          ? `${files.slice(0, 3).join(', ')} 외 ${files.length - 3}개`
          : files.join(', ');
        actions.push(`${action}: ${fileList}`);
      } else {
        actions.push(action);
      }
    }
  }

  return actions;
}

/**
 * 메시지들을 세션으로 그룹화합니다
 */
function groupIntoSessions(messages: Message[]): Session[] {
  const sessions: Session[] = [];
  let currentSession: Session | null = null;

  for (const msg of messages) {
    const isUser = msg.type === 'user' || msg.message?.role === 'user';
    const isAssistant = msg.type === 'assistant' || msg.message?.role === 'assistant';

    if (!isUser && !isAssistant) continue;

    const content = extractTextContent(msg);
    if (!content) continue;

    if (isUser) {
      // 유효한 사용자 요청인지 확인
      if (!isValidUserRequest(content)) {
        continue;
      }

      // 새로운 사용자 메시지가 오면 이전 세션 저장하고 새 세션 시작
      if (currentSession && currentSession.userRequests.length > 0) {
        sessions.push(currentSession);
      }

      currentSession = {
        userRequests: [],
        claudeActions: [],
        errors: [],
        filesModified: [],
        toolsUsed: [],
        timestamp: msg.timestamp || new Date().toISOString(),
      };

      if (!isNoiseMessage(content)) {
        currentSession.userRequests.push(content);
      }
    } else if (isAssistant && currentSession) {
      const { tools, files, errors } = extractToolInfo(msg);

      currentSession.toolsUsed.push(...tools);
      currentSession.filesModified.push(...files);
      currentSession.errors.push(...errors);

      // Claude의 텍스트 응답 (짧게)
      if (content && !isNoiseMessage(content) && content.length > 10) {
        const summary = content.length > 300 ? content.substring(0, 297) + '...' : content;
        if (!currentSession.claudeActions.includes(summary)) {
          currentSession.claudeActions.push(summary);
        }
      }
    }
  }

  // 마지막 세션 추가
  if (currentSession && currentSession.userRequests.length > 0) {
    sessions.push(currentSession);
  }

  return sessions;
}

/**
 * 원시 대화 데이터를 JSON 형식으로 출력합니다
 */
function outputRawData(sessions: Session[]): void {
  const rawData = sessions.map((session, index) => ({
    index: index + 1,
    timestamp: session.timestamp,
    userRequests: session.userRequests,
    toolsUsed: [...new Set(session.toolsUsed)],
    filesModified: [...new Set(session.filesModified)],
    errors: [...new Set(session.errors)],
    claudeResponse: session.claudeActions.length > 0
      ? session.claudeActions[session.claudeActions.length - 1]
      : null,
  }));

  console.log('\n=== RAW_SESSION_DATA_START ===');
  console.log(JSON.stringify(rawData, null, 2));
  console.log('=== RAW_SESSION_DATA_END ===');
}

/**
 * 상태를 로드합니다
 */
function loadState(projectPath: string): StateTracker | null {
  const stateFile = path.join(projectPath, STATE_FILE);

  if (fs.existsSync(stateFile)) {
    try {
      const content = fs.readFileSync(stateFile, 'utf-8');
      return JSON.parse(content);
    } catch (e) {
      return null;
    }
  }

  return null;
}

/**
 * 상태를 저장합니다
 */
function saveState(projectPath: string, state: StateTracker): void {
  const stateFile = path.join(projectPath, STATE_FILE);
  fs.writeFileSync(stateFile, JSON.stringify(state, null, 2));
}

export async function main(_args: string[]): Promise<void> {
  const projectPath = process.cwd();
  const state = loadState(projectPath);
  const lastTimestamp = state?.lastProcessedTimestamp;
  const previousTotal = state?.totalSessions || 0;

  console.log('📝 Claude Code 세션 문서화 도구\n');
  console.log(`프로젝트 경로: ${projectPath}`);

  if (lastTimestamp) {
    console.log(`📌 마지막 처리 시점: ${new Date(lastTimestamp).toLocaleString()}`);
    console.log(`📊 이전 처리 개수: ${previousTotal}개`);
  }

  const sessionFiles = findProjectSessionFiles(projectPath);

  if (sessionFiles.length === 0) {
    console.error('\n❌ 대화 내역을 찾을 수 없습니다.');
    console.error('   Claude Code로 이 프로젝트에서 대화를 나눈 적이 있는지 확인하세요.');
    process.exit(1);
  }

  console.log(`✓ ${sessionFiles.length}개의 세션 파일을 찾았습니다.`);

  let allMessages: Message[] = [];
  for (const file of sessionFiles) {
    const messages = readMessages(file, lastTimestamp);
    allMessages.push(...messages);
  }

  console.log(`✓ ${allMessages.length}개의 새로운 메시지를 읽었습니다.`);

  if (allMessages.length === 0) {
    console.log('\nℹ️ 새로운 대화 내역이 없습니다.');
    process.exit(0);
  }

  // 타임스탬프 순으로 정렬
  allMessages.sort((a, b) => {
    const timeA = a.timestamp ? new Date(a.timestamp).getTime() : 0;
    const timeB = b.timestamp ? new Date(b.timestamp).getTime() : 0;
    return timeA - timeB;
  });

  // 세션으로 그룹화
  const sessions = groupIntoSessions(allMessages);

  console.log(`✓ ${sessions.length}개의 대화 세션으로 그룹화했습니다.`);

  if (sessions.length === 0) {
    console.log('\nℹ️ 정리할 대화 내용이 없습니다.');
    process.exit(0);
  }

  // 원시 데이터 출력 (Claude가 후처리할 수 있도록)
  outputRawData(sessions);

  console.log(`\n📊 통계:`);
  console.log(`   - 추출된 세션: ${sessions.length}개`);
  console.log('\n✨ 데이터 추출 완료! Claude가 이 데이터를 분석하여 문서를 생성합니다.');
}

// CLI 진입점
if (require.main === module) {
  main(process.argv.slice(2)).catch(err => {
    console.error('에러 발생:', err.message);
    process.exit(1);
  });
}
